services:
  event-broker:
    image: rabbitmq:3-alpine
    container_name: rabbit-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672